### PR TITLE
TST: update .travis.yml to make tests env setup faster

### PR DESCRIPTION
**Pull request by aflaxman**

### CODE REVIEW

**Comment by aflaxman** [comment]
Hmm, it's more complicated than last time...

**Comment by aflaxman** [comment]
Using sudo isn’t possible (right now) #

http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#What-are-the-restrictions%3F

I wonder if it already has `npm` installed.

**Comment by aflaxman** [comment]
I'm confused that it says it is failing, because it passed for me https://travis-ci.org/aflaxman/mpld3/builds/71879389.  Maybe this is something about changing the `.travis.yml` file that confuses travis about what to run.

**Comment by danielballan** [comment]
I've made this change on a couple repos and never saw a failure. I'll take a closer look at work.

**Comment by danielballan** [comment]
@aflaxman Can you try generating a new commit hash and force-pushing?

**Comment by aflaxman** [comment]
If you tell me how... :)

**Comment by danielballan** [comment]
Haha, sure thing: amend the commit, which changes the timestamp and thus generates a different hash.

git commit --amend
git push origin branchname -f

**Comment by aflaxman** [comment]
Cool, I think that got it. :)

**Comment by jakevdp** [comment]
So this means npm is installed by default on Travis, yes?

**Comment by aflaxman** [comment]
Yes, now it is.  I'm going to merge.

**Pull request merged**
